### ISSUE TITLE
AWS EC2 VMs occasionally fail to register on initial boot

### ISSUE THREAD

**Issue by ejweber** [SUSE-Enceladus/cloud-regionsrv-client#125]
A Longhorn end-to-end test pipeline was previously running using AWS `ami-0dd7f664cbd69840b` (`suse-sles-15-sp4-v20230428-hvm-ssd-x86_64`). Terraform was (and is) used to create the VMs and then configure them. When we migrated to AWS `ami-04ce03e19570c1618` (`suse-sles-15-sp5-v20230719-hvm-ssd-x86_64`), we started to experience an issue where occasionally a node would not have any zypper repositories configured by the time our scripts started attempting to install packages. We saw this issue pretty often, though not always. While digging in, we found that this issue was caused by a failure in the registration scripts.

The old (always working) AMI used `v10.1.0` of this repo. The new (sometimes failing) AMI uses `v10.1.2`. It's not clear whether some change in this repo or a larger change between SP4 and SP5 leads to the occasional failure.

Please see https://github.com/longhorn/longhorn/issues/6504#issuecomment-1679277337 for logs and command output pulled from two nodes launched by the same Terraform operation. One of them did not fail to register and one did. In that comment, I suspected a temporary network problem (and maybe still do), but the exact mode of failure doesn't make total sense to me. The "bad" node appears to be able to contact and retrieve information from a "region server", but fails to communicate with any SMT. So it seems like the node's network is up and able to communicate externally, but registration still fails.

The workaround for us appears to be executing `sudo systemctl restart guestregister` when our user scripts start running. So far, this seems to always effectively get us registered so we can start installing packages.

**Comment by rjschwei** [comment]
Comment in  https://github.com/longhorn/longhorn/issues/6504#issuecomment-1679277337 . There were no changes in the connection code between the 2 versions noted. I would say it was more or less luck that no issues were observed with the previous version of the setup.
