### ISSUE TITLE
SUSE Azure update failures

### ISSUE THREAD

**Issue by jjedwa165** [SUSE-Enceladus/cloud-regionsrv-client#20]
We recently upgraded our SUSE SLES 12SP4 azure VMs. Afterwards all additional upgrades failed with the message:

```
Problem retrieving files from 'SLE-Module-Adv-Systems-Management12-Updates'.
Not all credentials files are eqivalent
Problem retrieving files from 'SLE-Module-Containers12-Updates'.
Not all credentials files are eqivalent
```

After reversing the issue via strace we discovered that the the ``susecloud`` zypper plugin as a apart of the ``cloud-regionsrv-client`` is comparing all files in ``/etc/zypp/credentials.d/`` to a base file as a precondition. While this normally works, our VMs **also** have other private repos with credential files in the same default [zypper credential location](https://doc.opensuse.org/projects/libzypp/12.3/group__ZyppConfig.html). 

Since these (private) credential files are different than the base SUSE ones all calls to resolve the the SUSE repo URLs ( e.g ``=plugin:/susecloud?`` ) via the ```urlresolver``` python code fail and none of our repos can refresh anymore. 

To try illustrate this I have suggested PR fix for the ``registerutils`` module. I'm hoping you will consider this as a mitigation for multiple private repos with different credentials using zypper.

**Comment by bear454** [comment]
Thanks for reporting; the primary maintainer is out on vacation; we'll review your contribution over the next few weeks.
